config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,
    length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, presence: true,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
    length: { maximum: 50 }

    def self.guest
      find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = "guestuser"
      end
    end


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body,)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.all
    @user = User.find(current_user.id)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Welcome! You have signed up successfully."
        redirect_to user_path(@user.id)
      else
        render :new
      end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag book.user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th>
                <%= @user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), {class:"btn btn-outline-secondary btn-block"} do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
          <%= form_with model: Book.new do |f| %>
            <label>Title</label>
            <br>
            <%= f.text_field :title, class:"form-control book_title" %>

            <label>Opinion</label>
            <br>
            <%= f.text_area :opinion, class:"form-control book_body" %>
            <%= f.submit "Create Book" %>
          <% end %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book, url: book_path do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title, autofocus: true, class:"form-control", autocomplete: "title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %><br />
          <%= f.text_area :body, class:"form-control", autocomplete: "body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <div class="row">
    <%= render '/users/user_info', user:current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.user do %>
                    <%= image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
              </td>
              <td><%= link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/user_info', user:@book.user %>
    <%= render '/'
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_profile_image(100,100) %><br />
              <%= link_to @book.user.name, user_path(@book.user) %>
            </td>
            <td><%= link_to @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), class:"btn btn-sm btn-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <span><i class="fas fa-book"></i></span>
      <strong>Bookers</strong>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <span><i class="fas fa-book"></i></span>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <span><i class="fas fa-book"></i></span>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9fcdeca566.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand"  href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" area-label="Toggle navigation">
            <span></span>
          </button>
            <div class="collapse navbar-collapse" id"=navbarNavDropDown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to current_user, class:"nav-link text-light" do %>
                      <span><i class="fas fa-home"></i></span>
                      Home
                    <% end %>
                  </li>
                  <li>
                    <%= link_to users_path, class:"nav-link text-light" do %>
                      <span><i class="fas fa-users"></i></span>
                      Users
                    <% end %>
                  </li>
                  <li>
                    <%= link_to books_path, class:"nav-link text-light" do %>
                      <span><i class="fas fa-book-open"></i></span>
                      Books
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
                      <span><i class="fas fa-sign-out-alt"></i></span>
                      Log out
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to root_path, class:"nav-link text-light" do %>
                      <span><i class="fas fa-home"></i></i></span>
                      Home
                    <% end %>
                  </li>
                  <li>
                    <%= link_to about_path, class:"nav-link text-light" do %>
                      <span><i class="fas fa-link"></i></i></span>
                      About
                    <% end %>
                  </li>
                  <li>
                    <%= link_to "/users/sign_up", class:"nav-link text-light" do %>
                      <span><i class="fas fa-user-plus"></i></span>
                      Sign up
                    <% end %>
                  </li>
                  <li>
                    <%= link_to "/users/sign_in", class:"nav-link text-light" do %>
                      <span><i class="fas fa-sign-in-alt"></i></span>
                      Log in
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image(100,100) %>
      <% else %>
        <%= image_tag 'default-image.jpg' %>
      <% end %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th>
                <%= @user.name %>
              </th>
            </tr>
            <tr>
              <th>introduction</th>
              <th>
                <%= @user.introduction %>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), {class:"btn btn-outline-secondary btn-block"} do %>
            <i class="fa-solid fa-user-gear"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
          <%= form_with model: Book.new do |f| %>
            <label>Title</label>
            <br>
            <%= f.text_field :title, class:"form-control book_title" %>
            <label>Opinion</label>
            <br>
            <%= f.text_area :opinion, class:"form-control book_body" %>
            <%= f.submit "Create Book" %>
          <% end %>
    </div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th>
          <%= user.name %>
        </th>
      </tr>
      <tr>
        <th>introduction</th>
        <th>
          <%= user.introduction %>
        </th>
      </tr>
    </tbody>
  </table>
  <% if user.name != "guestuser" %>
    <div class="row">
      <%= link_to edit_user_path(user), {class:"btn btn-outline-secondary btn-block"} do %>
      <span><i class="fas fa-user-cog"></i></span>
    <% end %>
  <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model: Book.new do |f| %>
    <label>Title</label>
    <br>
    <%= f.text_field :title, class:"form-control title" %>
    <label>Opinion</label>
    <br>
    <%= f.text_area :body, class:"form-control body" %>
    <br>
    <%= f.submit "Create Book", class:"btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true, class:"form-control", autocomplete: "name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %><br />
          <%= f.file_field :profile_image, class:"form-control-file user_image", accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction, class:"form-control introduction", autocomplete: "introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'user_info', user:current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th><%= image_tag user.get_profile_image(80,80) %></th>
              <th><%= user.name %></th>
              <th><%= link_to 'Show', user_path(user.id) %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= render '/users/user_info', user:@user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag book.user.get_profile_image(80,80) %></td>
              <td><%=link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>